export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUSET_ROBOTS_PENDING = "REQUSET_ROBOTS_PENDING";
export const REQUSET_ROBOTS_SUCCESS= "REQUSET_ROBOTS_SUCCESS";
export const REQUSET_ROBOTS_FAILED = "REQUSET_ROBOTS_FAILED";
